### ISSUE TITLE
Wrong type for `Content.asset`

### ISSUE THREAD

**Issue by mxdvl** [guardian/content-api-models#212]
There’s an issue in the asset type in `@guardian/content-api-models/v1/content`. The type is [declared as an enum](https://cdn.skypack.dev/-/@guardian/content-api-models@v17.3.0-WCIV6bHv2QOLqnOR2vpZ/dist=es2019,mode=imports/unoptimized/v1/assetType.d.ts?dts), when in fact it is a `string` that can be "image".

@Fweddi and I discovered this while building `the-guesser`: https://github.com/guardian/the-guesser/blob/3396e20149eb737492ae0cd8646a7adab1425ed8/vite-project/src/logic/extractors/extractMasterImageFile.ts#L8-L9

**Comment by davidfurey** [comment]
Also, these models are to be used with the CAPI Thrift output, not the CAPI json output.

**Comment by mxdvl** [comment]
No, this is correct, we were looking at the `AssetType` when accessing `Content` &rarr; `Element[]` &rarr; `Asset[]` &rarr; `AssetType`.

Ah! I thought these types were for the JSON output. Is there no such type declaration available? Happy to close if not.

**Comment by mxdvl** [comment]
> [Should] the "declared as an enum" link to [cdn.skypack.dev/-/@guardian/content-api-models@v17.3.0-WCIV6bHv2QOLqnOR2vpZ/dist=es2019,mode=imports/unoptimized/v1/assetType.d.ts?dts](https://cdn.skypack.dev/-/@guardian/content-api-models@v17.3.0-WCIV6bHv2QOLqnOR2vpZ/dist=es2019,mode=imports/unoptimized/v1/assetType.d.ts?dts) instead of [cdn.skypack.dev/-/@guardian/content-api-models@v17.3.0-WCIV6bHv2QOLqnOR2vpZ/dist=es2019,mode=imports/unoptimized/v1/contentType.d.ts?dts](https://cdn.skypack.dev/-/@guardian/content-api-models@v17.3.0-WCIV6bHv2QOLqnOR2vpZ/dist=es2019,mode=imports/unoptimized/v1/contentType.d.ts?dts) ?

Yes, I meant to link to the `AssetType`, thanks for catching it.
